### ISSUE TITLE
Mobile integration

### ISSUE THREAD

**Issue by FelipeCornejo** [J3lly-Been/YOLOv8-HumanDetection#1]
Hi, in wondering if that yolo model can be integrated using tensorflow lite for mobile app.
I need to export the model just with the .tflite extension?

**Comment by J3lly-Been** [comment]
Hi Felipe,

I'm not familiar with with integration of this model in a mobile environment, but it does sound interesting. I won't be of much help in this case but do look around and ask this same question in other forums.

Exited to see what you can do with this model :)
